### ISSUE TITLE
Convert to bfloat16 failing

### ISSUE THREAD

**Issue by mhillebrand** [stas00/ml-engineering#2]
I tried your shell script `torch-checkpoint-convert-to-bf16` on a quantized model with no .bin files, but it didn't quite work. Here are my results:

```bash
(gptq) ~/gptq/models/TheBloke_StableBeluga2-70B-GPTQ$ ll
total 34506488
-rw-rw-r-- 1 matt matt        7020 Jul 28 12:44 LICENSE.txt
-rw-rw-r-- 1 matt matt       15560 Jul 28 12:44 README.md
-rw-rw-r-- 1 matt matt        4766 Jul 28 12:44 USE_POLICY.md
-rw-rw-r-- 1 matt matt         679 Jul 28 12:44 config.json
-rw-rw-r-- 1 matt matt         137 Jul 28 12:44 generation_config.json
-rw-rw-r-- 1 matt matt 35332232456 Jul 28 12:49 gptq_model-4bit--1g.safetensors
-rw-rw-r-- 1 matt matt         301 Jul 28 12:44 huggingface-metadata.txt
-rw-rw-r-- 1 matt matt         183 Jul 28 12:49 quantize_config.json
-rw-rw-r-- 1 matt matt         411 Jul 28 12:49 special_tokens_map.json
-rw-rw-r-- 1 matt matt     1842764 Jul 28 12:49 tokenizer.json
-rw-rw-r-- 1 matt matt      499723 Jul 28 12:49 tokenizer.model
-rw-rw-r-- 1 matt matt         649 Jul 28 12:49 tokenizer_config.json

(gptq) ~/gptq/models/TheBloke_StableBeluga2-70B-GPTQ$ bash ~/mr/utilz/torch-checkpoint-convert-to-bf16 
creating a new checkpoint under dir bf16
converting *bin torch files
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <listcomp>
  File "/home/matt/miniconda3/envs/gptq/lib/python3.11/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/gptq/lib/python3.11/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/gptq/lib/python3.11/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '*bin'
converting *safetensors files
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <listcomp>
  File "/home/matt/miniconda3/envs/gptq/lib/python3.11/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/gptq/lib/python3.11/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/gptq/lib/python3.11/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '*bin'
the dir bf16 now contains a copy of the original checkpoint with bf16 weights

(gptq) ~/gptq/models/TheBloke_StableBeluga2-70B-GPTQ$ ll bf16/
total 2312
-rw-rw-r-- 1 matt matt     679 Aug 15 18:27 config.json
-rw-rw-r-- 1 matt matt     137 Aug 15 18:27 generation_config.json
-rw-rw-r-- 1 matt matt     183 Aug 15 18:27 quantize_config.json
-rw-rw-r-- 1 matt matt     411 Aug 15 18:27 special_tokens_map.json
-rw-rw-r-- 1 matt matt 1842764 Aug 15 18:27 tokenizer.json
-rw-rw-r-- 1 matt matt  499723 Aug 15 18:27 tokenizer.model
-rw-rw-r-- 1 matt matt     649 Aug 15 18:27 tokenizer_config.json
```

What are your thoughts? Thank you!

**Comment by stas00** [comment]
Hi @mhillebrand,

Indeed, the script needs `*.bin` files to do its work. It generates both types from bin files.

To work with `safetensors` as the source you will need to adapt it to use safetensors' `safe_open`+`get_tensor` as explained in its doc at https://github.com/huggingface/safetensors#getting-started.

If you can't figure it out I will have a time to look at it next week, but it should be fairly easy to do.
